/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'video' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
  'location' : IDL.Opt(IDL.Text),
  'images' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Property],
      [],
    ),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProperty' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Property],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'video' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
    'location' : IDL.Opt(IDL.Text),
    'images' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Property],
        [],
      ),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProperty' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Property],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };